# v1.0.1
server:
  port: 8080
spring:
  application:
    name: drawrun
  datasource:
    url: jdbc:mysql://13.124.222.21:3306/drawrun?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: dasima208
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  data:
    mongodb:
      host: 13.124.222.21
      port: 27017
      database: drawrun
      username: admin
      password: dasima208
      authentication-database: admin
    redis:
      host: redis-12597.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 12597
      password: ARGiUZe3GlOOL8fpfeAQPDp3Jb0JBtk7

mybatis:
  type-aliases-package: com.dasima.*.model
  mapper-locations: classpath:mapper/*.xml

jwt:
  header: Authorization
  secret: asjdaskdjfopixczujvioqapjweirjewqlkxcoivasadfasdfsqewrqwercxzvcasgdbasdfasddfasdfasdfasdfxzcvasdfewqr
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400
