# v1.0.3
server:
  port: 8080
kakao:
  api:
    key: "338aa1cf017cc92fccfe1c60b1b11270"
    url: "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
spring:
  application:
    name: drawrun
  datasource:
    url: jdbc:mysql://13.124.222.21:3306/drawrun?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: dasima208
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  data:
    mongodb:
      host: 13.124.222.21
      port: 27017
      database: drawrun
      username: admin
      password: dasima208
      authentication-database: admin
    redis:
      host: redis-12597.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 12597
      password: ARGiUZe3GlOOL8fpfeAQPDp3Jb0JBtk7
  mail:
    host: smtp.gmail.com
    port: 587
    username: drawrun247@gmail.com
    password: ukzndvpebtohvoor
    properties:
      mail.smtp.auth: true
      mail.smtp.debug: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000


mybatis:
  type-aliases-package: com.dasima.drawrun.domain.course.entity, com.dasima.drawrun.domain.masterpiece.entity
  mapper-locations: classpath:mapper/*.xml

jwt:
  header: Authorization
  secret: asjdaskdjfopixczujvioqapjweirjewqlkxcoivasadfasdfsqewrqwercxzvcasgdbasdfasddfasdfasdfasdfxzcvasdfewqr
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      accessKey: AKIAVA2MQME4E75NA67N
      secretKey: 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
    s3:
      bucket-name: drawrunbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false